name: Secure actionlint
description: |
  Securely run actionlint in a Docker container to lint GitHub Actions workflows while mitigating supply chain attacks.

inputs:
  configuration-path:
    required: false
    description: The path for the actionlint configurations.
  ignore:
    required: false
    description: Specify regular expressions to ignore actionlint error messages, one per line.

runs:
  using: composite

  steps:
    - name: Install
      id: install
      env:
        IMAGE_REPOSITORY: rhysd/actionlint
        IMAGE_DIGEST: sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9 # 1.7.7
      run: |
        echo "::group::Install"
        set -x
        image="${IMAGE_REPOSITORY}@${IMAGE_DIGEST}"
        echo "image=${image}" >> "${GITHUB_OUTPUT}"
        docker pull "${image}"
      shell: bash

    - name: Show version
      env:
        IMAGE: ${{ steps.install.outputs.image }}
      run: |
        echo "::group::Show version"
        set -x
        docker run --interactive --rm --read-only --user guest \
          --security-opt no-new-privileges --cap-drop all --network none \
          "${IMAGE}" --version
        echo "::endgroup::"
      shell: bash

    - name: Lint
      env:
        CONFIG_PATH: ${{ inputs.configuration-path }}
        IMAGE: ${{ steps.install.outputs.image }}
        IGNORE: ${{ inputs.ignore }}
      run: |
        echo "::group::Lint"
        set -x
        declare -a flags=(-color)
        if [[ "${CONFIG_PATH}" != "" ]]; then
          flags+=(-config-file "${CONFIG_PATH}")
        fi

        if [[ "${IGNORE}" != "" ]]; then
          while IFS= read -r regex; do
            [[ "${regex}" == "" ]] && continue
            flags+=("-ignore" "${regex}")
          done <<<"${IGNORE}"
        fi

        docker run --interactive --rm --read-only --user guest \
          --security-opt no-new-privileges --cap-drop all --network none \
          --volume "${PWD}:${PWD}:ro" --workdir "${PWD}" \
          "${IMAGE}" "${flags[@]}"
        echo "::endgroup::"
      shell: bash

branding:
  icon: check
  color: purple
